import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import AuthProvider from "@/app/auth/Provider";
import NavBar from "@/app/NavBar";

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-inter",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <AuthProvider>
                    <NavBar/>
                    <main>
                        {children}
                    </main>
                </AuthProvider>
            </body>
        </html>
    );
}
